### ISSUE TITLE
Multiple query parameters with same key aren't handled properly

### ISSUE THREAD

**Issue by bradvogel** [EventedMind/iron-router#1146]
Specify this route in your code:

```
Router.route('/testroute', function() {
  console.log(this.params.query)
}, {
  where: 'server'
});
```

Now load: localhost:3000/testroute?param=1&param=2

Expected result in console:
```
{
   "param": ["1", "2"]
}
```

Actual result in console:
```
{
   "param": "2"
}
```

**Comment by dburles** [comment]
Hey @bradvogel this is expected behavior, you need to pass the query params like `param[]=1&param[]=2` for them to be treated as an array

**Comment by bradvogel** [comment]
That isn't how the browser works though. The following form:
```
    <form action="/" method="get">
        <input name="param">
        <input name="param">
        <input type="submit">
    </form>
```

will submit to the url: `/?param=one&param=two`

**Comment by dburles** [comment]
just rename the field names to param[]

**Comment by bradvogel** [comment]
Yes, I see that's a workaround, but this is still a bug. The router should support arbitrarily name multiple parameters, as the spec allows.

**Comment by dburles** [comment]
I wouldn't say it's a bug. The router/whatever can choose to handle them however they wish and the convention of automatically coercing field names with square brackets into arrays is quite common and it makes handling things much less complicated. I know that Rails and Django (and pretty sure PHP) do the same thing.

**Comment by dburles** [comment]
Here's the issue @tmeasday opened with some reasoning behind the choice https://github.com/EventedMind/iron-url/issues/1

**Comment by bradvogel** [comment]
Ok, thanks for the help. I filed https://github.com/EventedMind/iron-url/issues/8 as a feature request. Closing this. Thanks!
