### ISSUE TITLE
Routing not working when in production, but works on localhost

### ISSUE THREAD

**Issue by mathieutozer** [EventedMind/iron-router#1168]
The routes work perfectly locally, but I get the default splash page when I deploy to a myapp.meteor.com  domain. I've searched for some documentation about configuration and found none, and a tiny test app works fine also. Any idea what I might be doing wrong?

**Comment by grantbachman** [comment]
Are you by any chance using Twitter Bootstrap? I ran into this same problem today, non-reproducible on localhost as well. After way too many hours of trying to reproduce this on a remote env with `meteor deploy xxxxx.meteor.com` I figured out that it was because of a file contained within Twitter Bootstrap. If you straight up download the .zip file of bootstrap and indiscriminately copy its 3 directories into your project (css/ fonts/ js/), `js/npm.js` will be copied along with it.

I think `js/npm.js` is only needed during the build process with Grunt, so I just deleted it. It solved the issue for me, although I'm not sure why...

**Comment by mathieutozer** [comment]
Hey thanks for the reply. I'm not using bootstrap. I guess I will just have to remove packages down until I discover the one that is broken for me...

**Comment by sembrador** [comment]
I have the same issue, my app works well in localhost but in production gets "iron:router Organize your Meteor application" message, I'm using Twitter Bootstrap but <code>js/npm.js</code> does not exist.
Another issue I'd noticed was I can't downgrade iron:router to a prior version.

>sembrador@some-server:~/webapp/myapp$ meteor remove iron:router
                                              
>Changes to your project's package version selections:
                                              
>iron:controller               removed from your project
>iron:core                       removed from your project
>iron:dynamic-template  removed from your project
>iron:layout                     removed from your project
>iron:location                  removed from your project
>iron:middleware-stack  removed from your project
>iron:router                     removed from your project
>iron:url                          removed from your project

>iron:router: removed dependency
>sembrador@some-server:~/webapp/myapp$ meteor add iron:router@1.0.4
                                              
>Changes to your project's package version selections:
                                              
>iron:controller               added, version 1.0.7
>iron:core                       added, version 1.0.7
>iron:dynamic-template  added, version 1.0.7
>iron:layout                     added, version 1.0.7
>iron:location                  added, version 1.0.7
>iron:middleware-stack  added, version 1.0.7
>iron:router                     added, version 1.0.7
>iron:url                          added, version 1.0.7

                                              
>iron:router: Routing specifically designed for Meteor
>sembrador@some-server:~/webapp/myapp$

Any help will be appreciated.

**Comment by mathieutozer** [comment]
I finally fixed my issue. It was caused by a JS error being thrown by some code which I was ignoring locally.

**Comment by sembrador** [comment]
I got a workaround for this behavior, by using <code>meteor build . --debug</code> my app runs well in production. I think it was something with minifying, I'm not sure but I'm still trying to deploy without the <code>--debug</code> parameter.

**Comment by v1nay** [comment]
@mathieutozer had the same error in production deploy my app which is working in develoment mode using `meteor` due to a JS error (visible on Developer Console in Chrome). Commenting the code causing the error allows the app to run well using `meteor --production`.

**Comment by neilyoung** [comment]
Having the same issue. Out of the blue, after "meteor add iron:router" I'm having this strange splash below my stuff

iron:router
Organize your Meteor application.

Router.route('/', function () {
  this.render('Home', {
    data: function () { return Items.findOne({_id: this.params._id}); }
  });
});
        
Check it out on Github:
https://github.com/eventedmind/iron-router 

And check out the new Guide:
https://eventedmind.github.io/iron-router

It disappears, once a route is defined. Strange thing.

**Comment by satyavh** [comment]
+1

**Comment by wcadam** [comment]
I am new to coding and I am having this issue with my very first test app that seems pretty simple. Anyone know where I can get some help?

**Comment by wcadam** [comment]
Directly after I posted this I figured out the issue was the existing code in the demo js. Once I deleted that code it worked perfectly. Probably a rookie mistake but I was able to fix it!

**Comment by phocks** [comment]
Thanks @mathieutozer I checked my Browser console and it was throwing a Javascript error. I fixed this error, and the iron:router splash screen went away.

**Comment by pal8** [comment]
+1

**Comment by pal8** [comment]
It works when using deploy with --debug. What does --debug do?

**Comment by stefan-wiesner** [comment]
Check your console in prod/build. For me it was a template name used twice in separate files.

**Comment by evansendra** [comment]
Thanks @mathieutozer and @v1nay ... finally solved after an hour of reading through threads and debugging

**Comment by mymedicalshopper** [comment]
Is there an alternative way to handle this besides fixing errors in other code? For instance, is there a way to detect this and then send someone to an error page? I am only experiencing this when using IE9/10. 

Perhaps this question even goes beyond just this specific page showing up... is there a best practice for cutting a user out of the iron:router flow and simply placing them at a static error page?

**Comment by evansendra** [comment]
+1 in my case iron router was configured correctly but a template name had a typo

**Comment by chrisbutler** [comment]
@mymedicalshopper you can customize that page now

**Comment by Archit1706** [comment]
I recently faced a similar issue where routing works fine on localhost but not when deployed
I solved it by re-deploying the website without using existing build cache and now routing works fine on production as well.
To give some more info I was creating a next js website (documentation type) and was deploying on Vercel.
