### ISSUE TITLE
Session is not defined

### ISSUE THREAD

**Issue by hiphapis** [EventedMind/iron-router#1175]
code:
```coffee
@route('somePath', path: '/some/:id', where: 'server')
  .get(->
    Session.set("message", "hahaha i'm session")
    path = Router.routes.home.path()
    @response.writeHead(301, Location: path)
    @response.end()
  )
```
then.. fire error `ReferenceError: Session is not defined`
how to load `Session` in `get`?

i did try `Session = new ReactiveDict('session') unless Session?` but it's does not work
error msg: `Error: Duplicate ReactiveDict name: session at Function.ReactiveDict._registerDictForMigrate `
(from: https://github.com/meteor/meteor/blob/c6a9c4abb0d9a565bd3934c392eeeb4f009f58fc/packages/session/session.js#L1)

and `ReactiveDict._dictsToMigrate['session']` is does not work too.
`ReactiveDict._dictsToMigrate['session']` is undefined

strange point
- `new ReactiveDict('session')` => duplicated.. it's mean is `session` is exist.
- so i call just `ReactiveDict._dictsToMigrate['session']` => undefined.. ;(

**Comment by copleykj** [comment]
This is a server side route.. Session is only available on the client.
