### ISSUE TITLE
Avoid iron router set % on blank spaces URL

### ISSUE THREAD

**Issue by Ethaan** [EventedMind/iron-router#1181]
I have this ``` Router.map function```
```javascript
Router.map(function () {
  this.route('perfil', {
    path: '/perfil/:nombre_usuario',
    data: function(){
        return Meteor.users.findOne({'profile.name': this.params.nombre_usuario});
        }
  });
});
```

and if you navigate to the page you got this
```
 perfil/Katya%20De%20La%20Rosa
```

Since the userName its
```Katya de la Rosa```,its there a way to avoid this?

**Comment by copleykj** [comment]
This is standard URL encoding and is probably being set by the browser not
iron-router.
