### ISSUE TITLE
contentFor and events

### ISSUE THREAD

**Issue by digilord** [EventedMind/iron-router#1198]
I have a template named `user` inside this template I have three contentFor block helpers that define some content to go into three sections of a header. Inside one of these blocks I have a `Done` button. This `Done` button is specific to the `user` template. I attached a click event to the `.done-button` class expecting that when I click the button I would get the output I expected. I am getting no console output.

Below is the gist that contains the code I am speaking of.

https://gist.github.com/digilord/0bfbccb09affb31e1a47

**Comment by digilord** [comment]
I was able to resolve this by using the template variation of the contentFor block.

**Comment by dj-foxxy** [comment]
This needs a big red warning sign somewhere. It's just stole hours of my life.

**Comment by crapthings** [comment]
@digilord hey can you share more detail how you problem get solved ?

i'm facing the same issue at the moment.

**Comment by daniel** [comment]
I also have the same problem and don't know how to solve it.
