### ISSUE TITLE
Using onBeforeAction hook causes meteor app to log user out after 1 or 2 refreshes

### ISSUE THREAD

**Issue by AnthonyReid99** [EventedMind/iron-router#1214]
I'm using the accounts-password@1.0.6 password with iron:router@1.0.6. Whenever I implement a global onBeforeAction hook, even if I do nothing in it, it causes the user to be logged out after 1 or 2 refreshes (usually 2). Sometimes this is accompanied by the removal of the user token (as with a proper logout), but most of the time it isn't. I'm logging in with Meteor.loginWithPassword(). No errors are logged anywhere.

**Comment by bipin244** [comment]
can you get solution for this problem?
